# secrets2.toml

OPENAI_API_KEY = "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"
LANGCHAIN_API_KEY = "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"
